[build-system]
requires = ["maturin>=1.6,<2.0"]
build-backend = "maturin"

[project]
name = "boltz-client-bindings"
dynamic = ["version"]
requires-python = ">=3.9"

[tool.maturin]
features = ["pyo3/extension-module"]
